services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$TYPEORM_USER
      - POSTGRES_PASSWORD=$TYPEORM_PASS
      - POSTGRES_DB=$TYPEORM_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - TYPEORM_HOST=db
    networks:
      - backend
networks:
  backend:
    driver: bridge
